version: '3.8'
services:
  unit:
    image: nginx/unit:1.29.1-python3.11
    volumes:
      - ./app:/www/app
      - ./unit-config.json:/docker-entrypoint.d/unit-config.json
    ports:
      - "8080:8080"
