version: '3.8'
services:
  unit:
    image: nginx/unit:1.29.1-python3.11
    volumes:
      - ./app:/www/app
      - ./unit-config.json:/docker-entrypoint.d/unit-config.json
    ports:
      - "${UNIT_BACKEND_PORT:-18080}:8080"
    depends_on:
      - hello

  hello:
    build: ./hello_app
    ports:
      - "8000:8000"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  esdata:
