version: '3.8'
services:
  unit:
    image: nginx/unit:1.29.1-python3.11
    volumes:
      - ./app:/www/app
      - ./unit-config.json:/docker-entrypoint.d/unit-config.json
    ports:
      - "${UNIT_PORT:-8090}:8080"
    depends_on:
      - hello

  hello:
    build: ./hello_app
    ports:
      - "8000:8000"
